# ──────────────────────────────────────────────────────────
# V5.0 Backend — Provider Priority Map
# ──────────────────────────────────────────────────────────
#
# For each sport, lists the data providers for every data
# type in order of merge priority (first = highest).
# Provider names match their directory names under data/raw/.
# When merging, non-null fields from lower-priority providers
# are preserved; conflicting fields use the higher-priority value.
# ──────────────────────────────────────────────────────────

from __future__ import annotations

from typing import TypeAlias

ProviderList: TypeAlias = list[str]
DataTypeMap: TypeAlias = dict[str, ProviderList]

# ── Master provider priority ─────────────────────────────

PROVIDER_PRIORITY: dict[str, DataTypeMap] = {
    # ── Basketball ────────────────────────────────────────
    "nba": {
        "games":        ["espn", "nbastats"],
        "teams":        ["espn", "nbastats"],
        "players":      ["nbastats", "espn"],
        "standings":    ["nbastats", "espn"],
        "player_stats": ["nbastats", "espn"],
        "odds":         ["odds", "espn", "oddsapi"],
        "player_props": ["odds", "oddsapi", "prizepicks"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      [],
        "team_stats":   ["espn"],
        "transactions": ["espn"],
    },
    "wnba": {
        "games":        ["espn"],
        "teams":        ["espn"],
        "players":      ["nbastats", "espn"],
        "standings":    ["espn"],
        "player_stats": ["nbastats", "espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      [],
        "team_stats":   ["espn"],
        "transactions": ["espn"],
    },
    "ncaab": {
        "games":        ["espn"],
        "teams":        ["espn"],
        "players":      ["espn"],
        "standings":    ["espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      [],
        "team_stats":   ["espn"],
        "transactions": ["espn"],
    },
    "ncaaw": {
        "games":        ["espn"],
        "teams":        ["espn"],
        "players":      ["espn"],
        "standings":    ["espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      [],
        "team_stats":   ["espn"],
        "transactions": ["espn"],
    },

    # ── Football ──────────────────────────────────────────
    "nfl": {
        "games":        ["espn"],
        "teams":        ["espn"],
        "players":      ["espn"],
        "standings":    ["espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "espn", "oddsapi"],
        "player_props": ["odds", "oddsapi", "prizepicks"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
        "team_stats":   ["espn"],
        "transactions": ["espn"],
    },
    "ncaaf": {
        "games":        ["cfbdata", "espn"],
        "teams":        ["cfbdata", "espn"],
        "players":      ["cfbdata", "espn"],
        "standings":    ["cfbdata", "espn"],
        "player_stats": ["cfbdata", "espn"],
        "odds":         ["odds", "cfbdata", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
        "team_stats":   ["cfbdata", "espn"],
        "transactions": ["espn"],
    },

    # ── Baseball ──────────────────────────────────────────
    "mlb": {
        "games":        ["mlbstats", "espn", "lahman"],
        "teams":        ["mlbstats", "espn", "lahman"],
        "players":      ["mlbstats", "lahman", "espn"],
        "standings":    ["mlbstats", "espn", "lahman"],
        "player_stats": ["mlbstats", "lahman", "espn"],
        "team_game_stats": ["mlbstats"],
        "batter_game_stats": ["mlbstats"],
        "pitcher_game_stats": ["mlbstats"],
        "odds":         ["odds", "espn", "oddsapi"],
        "player_props": ["odds", "oddsapi", "prizepicks"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
        "team_stats":   ["espn"],
        "transactions": ["espn"],
    },

    # ── Hockey ────────────────────────────────────────────
    "nhl": {
        "games":        ["nhl", "espn"],
        "teams":        ["espn"],
        "players":      ["nhl", "espn"],
        "standings":    ["nhl", "espn"],
        "player_stats": ["nhl", "espn"],
        "odds":         ["odds", "espn", "oddsapi"],
        "player_props": ["odds", "oddsapi", "prizepicks"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      [],
        "team_stats":   ["espn"],
        "transactions": ["espn"],
    },

    # ── Soccer ────────────────────────────────────────────
    "epl": {
        "games":        ["footballdata", "statsbomb", "espn", "understat"],
        "teams":        ["espn", "statsbomb"],
        "players":      ["statsbomb", "footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["statsbomb", "espn", "understat"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "laliga": {
        "games":        ["statsbomb", "espn", "understat"],
        "teams":        ["espn", "statsbomb"],
        "players":      ["statsbomb", "espn"],
        "standings":    ["espn"],
        "player_stats": ["statsbomb", "espn", "understat"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "bundesliga": {
        "games":        ["statsbomb", "espn", "understat"],
        "teams":        ["espn", "statsbomb"],
        "players":      ["statsbomb", "espn"],
        "standings":    ["espn"],
        "player_stats": ["statsbomb", "espn", "understat"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "seriea": {
        "games":        ["statsbomb", "espn", "understat"],
        "teams":        ["espn", "statsbomb"],
        "players":      ["statsbomb", "espn"],
        "standings":    ["espn"],
        "player_stats": ["statsbomb", "espn", "understat"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "ligue1": {
        "games":        ["statsbomb", "espn", "understat"],
        "teams":        ["espn", "statsbomb"],
        "players":      ["statsbomb", "espn"],
        "standings":    ["espn"],
        "player_stats": ["statsbomb", "espn", "understat"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "mls": {
        "games":        ["statsbomb", "espn"],
        "teams":        ["espn"],
        "players":      ["statsbomb", "espn"],
        "standings":    ["espn"],
        "player_stats": ["statsbomb", "espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "ucl": {
        "games":        ["statsbomb", "espn"],
        "teams":        ["espn", "statsbomb"],
        "players":      ["statsbomb", "espn"],
        "standings":    ["espn"],
        "player_stats": ["statsbomb", "espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "nwsl": {
        "games":        ["statsbomb", "espn"],
        "teams":        ["espn"],
        "players":      ["statsbomb", "espn"],
        "standings":    ["espn"],
        "player_stats": ["statsbomb", "espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "ligamx": {
        "games":        ["espn"],
        "teams":        ["espn"],
        "players":      ["espn"],
        "standings":    ["espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "europa": {
        "games":        ["footballdata", "espn"],
        "teams":        ["footballdata", "espn"],
        "players":      ["footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },

    # ── Additional top-flight leagues ─────────────────────────
    "eredivisie": {
        "games":        ["footballdata", "espn"],
        "teams":        ["footballdata", "espn"],
        "players":      ["footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "primeiraliga": {
        "games":        ["footballdata", "espn"],
        "teams":        ["footballdata", "espn"],
        "players":      ["footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },

    # ── Second divisions ──────────────────────────────────────
    "championship": {
        "games":        ["footballdata", "espn"],
        "teams":        ["footballdata", "espn"],
        "players":      ["footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "bundesliga2": {
        "games":        ["footballdata", "espn"],
        "teams":        ["footballdata", "espn"],
        "players":      ["footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "serieb": {
        "games":        ["footballdata", "espn"],
        "teams":        ["footballdata", "espn"],
        "players":      ["footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "ligue2": {
        "games":        ["footballdata", "espn"],
        "teams":        ["footballdata", "espn"],
        "players":      ["footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },

    # ── International tournaments ─────────────────────────────
    "worldcup": {
        "games":        ["footballdata", "espn"],
        "teams":        ["footballdata", "espn"],
        "players":      ["footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     [],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "euros": {
        "games":        ["footballdata", "espn"],
        "teams":        ["footballdata", "espn"],
        "players":      ["footballdata", "espn"],
        "standings":    ["footballdata", "espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     [],
        "news":         ["espn"],
        "weather":      ["weather"],
    },

    # ── Motorsport ────────────────────────────────────────
    "f1": {
        "games":        ["openf1", "ergast", "espn"],
        "teams":        ["ergast", "espn"],
        "players":      ["openf1", "ergast", "espn"],
        "standings":    ["ergast", "espn"],
        "player_stats": ["openf1", "ergast"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     [],
        "news":         [],
        "weather":      ["weather"],
    },
    "indycar": {
        "games":        ["espn"],
        "teams":        ["espn"],
        "players":      ["espn"],
        "standings":    ["espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     [],
        "news":         ["espn"],
        "weather":      ["weather"],
    },

    # ── Tennis ────────────────────────────────────────────
    "atp": {
        "games":        ["tennisabstract", "espn"],
        "teams":        [],
        "players":      ["tennisabstract", "espn"],
        "standings":    ["tennisabstract", "espn"],
        "player_stats": ["tennisabstract", "espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     [],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "wta": {
        "games":        ["tennisabstract", "espn"],
        "teams":        [],
        "players":      ["tennisabstract", "espn"],
        "standings":    ["tennisabstract", "espn"],
        "player_stats": ["tennisabstract", "espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     [],
        "news":         ["espn"],
        "weather":      ["weather"],
    },

    # ── MMA ───────────────────────────────────────────────
    "ufc": {
        "games":        ["ufcstats"],
        "teams":        [],
        "players":      ["ufcstats"],
        "standings":    [],
        "player_stats": ["ufcstats"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi", "prizepicks"],
        "injuries":     [],
        "news":         [],
        "weather":      [],
    },

    # ── Esports ───────────────────────────────────────────
    "lol": {
        "games":        ["pandascore"],
        "teams":        ["pandascore"],
        "players":      ["pandascore"],
        "standings":    ["pandascore"],
        "player_stats": ["pandascore"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     [],
        "news":         [],
        "weather":      [],
    },
    "csgo": {
        "games":        ["pandascore"],
        "teams":        ["pandascore"],
        "players":      ["pandascore"],
        "standings":    ["pandascore"],
        "player_stats": ["pandascore"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     [],
        "news":         [],
        "weather":      [],
    },
    "dota2": {
        "games":        ["opendota", "pandascore"],
        "teams":        ["pandascore", "opendota"],
        "players":      ["pandascore", "opendota"],
        "standings":    ["pandascore", "opendota"],
        "player_stats": ["opendota", "pandascore"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     [],
        "news":         [],
        "weather":      [],
    },
    "valorant": {
        "games":        ["pandascore"],
        "teams":        ["pandascore"],
        "players":      ["pandascore"],
        "standings":    ["pandascore"],
        "player_stats": ["pandascore"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     [],
        "news":         [],
        "weather":      [],
    },

    # ── Golf ──────────────────────────────────────────────
    "golf": {
        "games":        ["espn"],
        "teams":        [],
        "players":      ["espn"],
        "standings":    ["espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": ["odds", "oddsapi"],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
    "lpga": {
        "games":        ["espn"],
        "teams":        [],
        "players":      ["espn"],
        "standings":    ["espn"],
        "player_stats": ["espn"],
        "odds":         ["odds", "oddsapi"],
        "player_props": [],
        "injuries":     ["espn"],
        "news":         ["espn"],
        "weather":      ["weather"],
    },
}


# ── Helpers ───────────────────────────────────────────────

ALL_DATA_TYPES: list[str] = [
    "games",
    "teams",
    "players",
    "standings",
    "player_stats",
    "odds",
    "player_props",
    "injuries",
    "news",
    "weather",
    "team_stats",
    "transactions",
    "team_game_stats",
    "batter_game_stats",
    "pitcher_game_stats",
    "market_signals",
    "schedule_fatigue",
]


def providers_for(sport: str, data_type: str) -> ProviderList:
    """Return the priority-ordered provider list for *sport* / *data_type*."""
    return PROVIDER_PRIORITY.get(sport, {}).get(data_type, [])


def all_providers(sport: str) -> set[str]:
    """Return the distinct set of providers used by *sport* across all data types."""
    providers: set[str] = set()
    for dt_providers in PROVIDER_PRIORITY.get(sport, {}).values():
        providers.update(dt_providers)
    return providers
