[pytest]
filterwarnings =
	ignore:.*numpy.core.numeric is deprecated.*:DeprecationWarning
	ignore:.*If you are loading a serialized model.*:UserWarning
	ignore:.*'oneOf' deprecated.*:DeprecationWarning
	ignore:.*'parseString' deprecated.*:DeprecationWarning
	ignore:.*'resetCache' deprecated.*:DeprecationWarning
