/**
 * Zod schemas matching the v5.0 backend Pydantic models.
 */
import { z } from "zod";

// ── Base ─────────────────────────────────────────────────────────────────────

const baseFields = {
  source: z.string().default("unknown"),
};

// ── Game ─────────────────────────────────────────────────────────────────────

const optNum = z.number().nullable().optional();
const optStr = z.string().nullable().optional();

export const GameSchema = z.object({
  ...baseFields,
  id: z.string(),
  sport: z.string(),
  season: z.string(),
  date: z.string(),
  status: z.string().default("scheduled"),
  home_team: z.string(),
  away_team: z.string(),
  home_score: optNum,
  away_score: optNum,
  home_team_id: optStr,
  away_team_id: optStr,
  venue: optStr,
  attendance: optNum,
  weather: optStr,
  broadcast: optStr,
  broadcast_url: optStr,
  start_time: optStr,
  period: optStr,
  is_neutral_site: z.boolean().default(false),

  // Linescore — quarters (basketball, football)
  home_q1: optNum,
  home_q2: optNum,
  home_q3: optNum,
  home_q4: optNum,
  home_ot: optNum,
  away_q1: optNum,
  away_q2: optNum,
  away_q3: optNum,
  away_q4: optNum,
  away_ot: optNum,

  // Linescore — periods (hockey)
  home_p1: optNum,
  home_p2: optNum,
  home_p3: optNum,
  away_p1: optNum,
  away_p2: optNum,
  away_p3: optNum,

  // Linescore — innings (baseball)
  home_i1: optNum,
  home_i2: optNum,
  home_i3: optNum,
  home_i4: optNum,
  home_i5: optNum,
  home_i6: optNum,
  home_i7: optNum,
  home_i8: optNum,
  home_i9: optNum,
  home_extras: optNum,
  away_i1: optNum,
  away_i2: optNum,
  away_i3: optNum,
  away_i4: optNum,
  away_i5: optNum,
  away_i6: optNum,
  away_i7: optNum,
  away_i8: optNum,
  away_i9: optNum,
  away_extras: optNum,

  // Half scores (college basketball, soccer)
  home_h1_score: optNum,
  home_h2_score: optNum,
  away_h1_score: optNum,
  away_h2_score: optNum,

  // Baseball summary stats (R/H/E)
  home_runs: optNum,
  away_runs: optNum,
  home_hits: optNum,
  away_hits: optNum,

  // Baseball detailed stats
  home_at_bats: optNum,
  away_at_bats: optNum,
  home_rbi: optNum,
  away_rbi: optNum,
  home_home_runs: optNum,
  away_home_runs: optNum,
  home_walks: optNum,
  away_walks: optNum,
  home_strikeouts: optNum,
  away_strikeouts: optNum,
  home_stolen_bases: optNum,
  away_stolen_bases: optNum,
  home_batting_avg: optNum,
  away_batting_avg: optNum,
  home_obp: optNum,
  away_obp: optNum,
  home_slg: optNum,
  away_slg: optNum,
  home_ops: optNum,
  away_ops: optNum,
  home_whip: optNum,
  away_whip: optNum,
  home_earned_runs: optNum,
  away_earned_runs: optNum,
  home_era: optNum,
  away_era: optNum,
  home_innings_pitched: optNum,
  away_innings_pitched: optNum,
  home_pitches_thrown: optNum,
  away_pitches_thrown: optNum,
  home_plate_appearances: optNum,
  away_plate_appearances: optNum,
  home_doubles: optNum,
  away_doubles: optNum,
  home_triples: optNum,
  away_triples: optNum,
  home_total_bases: optNum,
  away_total_bases: optNum,
  home_errors: optNum,
  away_errors: optNum,
  home_left_on_base: optNum,
  away_left_on_base: optNum,
  home_pitching_strikeouts: optNum,
  away_pitching_strikeouts: optNum,
  home_pitching_walks: optNum,
  away_pitching_walks: optNum,
  home_k_rate: optNum,
  away_k_rate: optNum,
  home_bb_rate: optNum,
  away_bb_rate: optNum,
  home_iso: optNum,
  away_iso: optNum,

  // Soccer team stats
  home_possession: optNum,
  away_possession: optNum,
  home_shots: optNum,
  away_shots: optNum,
  home_total_shots: optNum,
  away_total_shots: optNum,
  home_shots_on_target: optNum,
  away_shots_on_target: optNum,
  home_corners: optNum,
  away_corners: optNum,
  home_fouls: optNum,
  away_fouls: optNum,
  home_offsides: optNum,
  away_offsides: optNum,
  home_tackles: optNum,
  away_tackles: optNum,
  home_interceptions: optNum,
  away_interceptions: optNum,
  home_clearances: optNum,
  away_clearances: optNum,
  home_accurate_passes: optNum,
  away_accurate_passes: optNum,
  home_total_passes: optNum,
  away_total_passes: optNum,
  home_pass_pct: optNum,
  away_pass_pct: optNum,
  home_crosses: optNum,
  away_crosses: optNum,
  home_long_balls: optNum,
  away_long_balls: optNum,
  home_yellow_cards: optNum,
  away_yellow_cards: optNum,
  home_red_cards: optNum,
  away_red_cards: optNum,
  home_saves: optNum,
  away_saves: optNum,
  home_penalty_goals: optNum,
  away_penalty_goals: optNum,
  home_penalty_shots: optNum,
  away_penalty_shots: optNum,

  // Soccer advanced stats
  home_shots_on_target_pct: optNum,
  away_shots_on_target_pct: optNum,
  home_shot_conversion_rate: optNum,
  away_shot_conversion_rate: optNum,
  home_shot_pct: optNum,
  away_shot_pct: optNum,
  home_tackle_pct: optNum,
  away_tackle_pct: optNum,
  home_xg: optNum,
  away_xg: optNum,
  home_accurate_crosses: optNum,
  away_accurate_crosses: optNum,
  home_total_crosses: optNum,
  away_total_crosses: optNum,

  // Basketball team stats
  home_fg_pct: optNum,
  away_fg_pct: optNum,
  home_three_pct: optNum,
  away_three_pct: optNum,
  home_ft_pct: optNum,
  away_ft_pct: optNum,
  home_rebounds: optNum,
  away_rebounds: optNum,
  home_assists: optNum,
  away_assists: optNum,
  home_steals: optNum,
  away_steals: optNum,
  home_blocks: optNum,
  away_blocks: optNum,
  home_turnovers: optNum,
  away_turnovers: optNum,

  // Basketball advanced stats
  home_offensive_rebounds: optNum,
  away_offensive_rebounds: optNum,
  home_defensive_rebounds: optNum,
  away_defensive_rebounds: optNum,
  home_possessions: optNum,
  away_possessions: optNum,
  home_true_shooting_pct: optNum,
  away_true_shooting_pct: optNum,
  home_effective_fg_pct: optNum,
  away_effective_fg_pct: optNum,
  home_points_in_paint: optNum,
  away_points_in_paint: optNum,
  home_fast_break_points: optNum,
  away_fast_break_points: optNum,
  home_largest_lead: optNum,
  away_largest_lead: optNum,

  // Football team stats
  home_total_yards: optNum,
  away_total_yards: optNum,
  home_passing_yards: optNum,
  away_passing_yards: optNum,
  home_rushing_yards: optNum,
  away_rushing_yards: optNum,
  home_first_downs: optNum,
  away_first_downs: optNum,
  home_turnovers_football: optNum,
  away_turnovers_football: optNum,
  home_sacks: optNum,
  away_sacks: optNum,
  home_penalties: optNum,
  away_penalties: optNum,
  home_penalty_yards: optNum,
  away_penalty_yards: optNum,
  home_third_down_pct: optNum,
  away_third_down_pct: optNum,
  home_time_of_possession: optStr,
  away_time_of_possession: optStr,
  home_completion_pct: optNum,
  away_completion_pct: optNum,
  home_fumbles_lost: optNum,
  away_fumbles_lost: optNum,
  home_interceptions_thrown: optNum,
  away_interceptions_thrown: optNum,
  home_passing_touchdowns: optNum,
  away_passing_touchdowns: optNum,
  home_rushing_touchdowns: optNum,
  away_rushing_touchdowns: optNum,
  home_fourth_down_pct: optNum,
  away_fourth_down_pct: optNum,
  home_red_zone_pct: optNum,
  away_red_zone_pct: optNum,
  home_total_drives: optNum,
  away_total_drives: optNum,
  home_defensive_tds: optNum,
  away_defensive_tds: optNum,
  home_turnover_margin: optNum,
  away_turnover_margin: optNum,

  // Hockey team stats
  home_shots_on_goal: optNum,
  away_shots_on_goal: optNum,
  home_power_play_goals: optNum,
  away_power_play_goals: optNum,
  home_power_play_attempts: optNum,
  away_power_play_attempts: optNum,
  home_power_play_pct: optNum,
  away_power_play_pct: optNum,
  home_penalty_minutes: optNum,
  away_penalty_minutes: optNum,
  home_faceoffs_won: optNum,
  away_faceoffs_won: optNum,
  home_faceoffs_total: optNum,
  away_faceoffs_total: optNum,
  home_faceoffs_lost: optNum,
  away_faceoffs_lost: optNum,
  home_faceoff_pct: optNum,
  away_faceoff_pct: optNum,
  home_blocked_shots: optNum,
  away_blocked_shots: optNum,
  home_hits_nhl: optNum,
  away_hits_nhl: optNum,
  home_takeaways: optNum,
  away_takeaways: optNum,
  home_giveaways: optNum,
  away_giveaways: optNum,
  home_shorthanded_goals: optNum,
  away_shorthanded_goals: optNum,
  home_penalty_kill_pct: optNum,
  away_penalty_kill_pct: optNum,
  home_save_pct: optNum,
  away_save_pct: optNum,
  home_shooting_pct: optNum,
  away_shooting_pct: optNum,

  // Tennis game-level stats
  home_aces: optNum,
  away_aces: optNum,
  home_double_faults: optNum,
  away_double_faults: optNum,
  home_first_serve_pct: optNum,
  away_first_serve_pct: optNum,
  home_break_points_won: optNum,
  away_break_points_won: optNum,
  home_break_points_total: optNum,
  away_break_points_total: optNum,
  home_break_point_conversion_pct: optNum,
  away_break_point_conversion_pct: optNum,
  home_break_point_save_pct: optNum,
  away_break_point_save_pct: optNum,
  home_ace_df_ratio: optNum,
  away_ace_df_ratio: optNum,
  total_sets: optNum,
  home_sets_won: optNum,
  away_sets_won: optNum,

  // Esports game-level stats
  home_kills: optNum,
  away_kills: optNum,
  home_deaths: optNum,
  away_deaths: optNum,
  home_kill_death_ratio: optNum,
  away_kill_death_ratio: optNum,
  home_gold: optNum,
  away_gold: optNum,
  home_gold_per_min: optNum,
  away_gold_per_min: optNum,
  duration: optNum,
  game_duration: optNum,
  map_name: optStr,
  total_rounds: optNum,
}).passthrough();
export type Game = z.infer<typeof GameSchema>;

// ── Team ─────────────────────────────────────────────────────────────────────

export const TeamSchema = z.object({
  ...baseFields,
  id: z.string(),
  sport: z.string(),
  name: z.string(),
  abbreviation: z.string().nullable().optional(),
  city: z.string().nullable().optional(),
  conference: z.string().nullable().optional(),
  division: z.string().nullable().optional(),
  league: z.string().nullable().optional(),
  logo_url: z.string().nullable().optional(),
  color_primary: z.string().nullable().optional(),
  color_secondary: z.string().nullable().optional(),
  venue_name: z.string().nullable().optional(),
  founded_year: z.number().nullable().optional(),
});
export type Team = z.infer<typeof TeamSchema>;

// ── Player ───────────────────────────────────────────────────────────────────

export const PlayerSchema = z.object({
  ...baseFields,
  id: z.string(),
  sport: z.string(),
  name: z.string(),
  team_id: z.string().nullable().optional(),
  position: z.string().nullable().optional(),
  jersey_number: z.number().nullable().optional(),
  height: z.string().nullable().optional(),
  weight: z.number().nullable().optional(),
  birth_date: z.string().nullable().optional(),
  nationality: z.string().nullable().optional(),
  experience_years: z.number().nullable().optional(),
  status: z.string().default("active"),
  headshot_url: z.string().nullable().optional(),
  team_name: z.string().nullable().optional(),
  team_abbreviation: z.string().nullable().optional(),
});
export type Player = z.infer<typeof PlayerSchema>;

// ── Standing ─────────────────────────────────────────────────────────────────

export const StandingSchema = z.object({
  ...baseFields,
  team_id: z.string(),
  team_name: z.string().nullable().optional(),
  sport: z.string(),
  season: z.string(),
  wins: z.number().default(0),
  losses: z.number().default(0),
  ties: z.number().nullable().optional(),
  otl: z.number().nullable().optional(),
  pct: z.number().nullable().optional(),
  games_played: z.number().nullable().optional(),
  points_for: z.number().nullable().optional(),
  points_against: z.number().nullable().optional(),
  points: z.number().nullable().optional(),
  rank: z.number().nullable().optional(),
  group: z.string().nullable().optional(),
  conference: z.string().nullable().optional(),
  division: z.string().nullable().optional(),
  conference_rank: z.number().nullable().optional(),
  division_rank: z.number().nullable().optional(),
  overall_rank: z.number().nullable().optional(),
  streak: z.string().nullable().optional(),
  last_ten: z.string().nullable().optional(),
  home_record: z.string().nullable().optional(),
  away_record: z.string().nullable().optional(),
  clinch_status: z.string().nullable().optional(),
});
export type Standing = z.infer<typeof StandingSchema>;

// ── Odds ─────────────────────────────────────────────────────────────────────

export const OddsSchema = z.object({
  ...baseFields,
  game_id: z.string(),
  sport: z.string(),
  bookmaker: z.string(),
  home_team: z.string().nullable().optional(),
  away_team: z.string().nullable().optional(),
  h2h_home: z.number().nullable().optional(),
  h2h_away: z.number().nullable().optional(),
  h2h_draw: z.number().nullable().optional(),
  spread_home: z.number().nullable().optional(),
  spread_away: z.number().nullable().optional(),
  spread_home_line: z.number().nullable().optional(),
  spread_away_line: z.number().nullable().optional(),
  total_over: z.number().nullable().optional(),
  total_under: z.number().nullable().optional(),
  total_line: z.number().nullable().optional(),
  timestamp: z.string().nullable().optional(),
  is_live: z.boolean().default(false),
});
export type Odds = z.infer<typeof OddsSchema>;

// ── Market Signals ───────────────────────────────────────────────────────────

export const MarketSignalSchema = z.object({
  ...baseFields,
  game_id: z.string(),
  sport: z.string(),
  season: z.string().nullable().optional(),
  bookmaker: z.string().nullable().optional(),
  market_regime: z.string().nullable().optional(),
  date: z.string().nullable().optional(),
  home_team: z.string().nullable().optional(),
  away_team: z.string().nullable().optional(),
}).passthrough();
export type MarketSignal = z.infer<typeof MarketSignalSchema>;

// ── Schedule Fatigue ─────────────────────────────────────────────────────────

export const ScheduleFatigueSchema = z.object({
  ...baseFields,
  game_id: z.string(),
  sport: z.string(),
  season: z.string().nullable().optional(),
  team_id: z.string().nullable().optional(),
  fatigue_level: z.string().nullable().optional(),
  fatigue_score: z.number().nullable().optional(),
  date: z.string().nullable().optional(),
}).passthrough();
export type ScheduleFatigue = z.infer<typeof ScheduleFatigueSchema>;

// ── Injury ───────────────────────────────────────────────────────────────────

export const InjurySchema = z.object({
  ...baseFields,
  player_id: z.string(),
  sport: z.string(),
  team_id: z.string().nullable().optional(),
  player_name: z.string().nullable().optional(),
  status: z.string(),
  description: z.string().nullable().optional(),
  body_part: z.string().nullable().optional(),
  return_date: z.string().nullable().optional(),
  reported_at: z.string().nullable().optional(),
});
export type Injury = z.infer<typeof InjurySchema>;

// ── Prediction ───────────────────────────────────────────────────────────────

export const PredictionSchema = z.object({
  ...baseFields,
  game_id: z.string(),
  sport: z.string(),
  model: z.string().optional(),
  home_team: z.string().optional(),
  away_team: z.string().optional(),
  home_win_prob: z.number().nullable().optional(),
  away_win_prob: z.number().nullable().optional(),
  draw_prob: z.number().nullable().optional(),
  predicted_spread: z.number().nullable().optional(),
  predicted_total: z.number().nullable().optional(),
  predicted_home_score: z.number().nullable().optional(),
  predicted_away_score: z.number().nullable().optional(),
  confidence: z.number().nullable().optional(),
  consensus: z.number().nullable().optional(),
  n_models: z.number().nullable().optional(),
  features_hash: z.string().nullable().optional(),
  timestamp: z.string().optional(),
  date: z.string().optional(),
  created_at: z.string().optional(),
});
export type Prediction = z.infer<typeof PredictionSchema>;

// ── News ─────────────────────────────────────────────────────────────────────

export const NewsSchema = z.object({
  ...baseFields,
  id: z.string().optional(),
  sport: z.string(),
  headline: z.string(),
  description: z.string().nullable().optional(),
  link: z.string().nullable().optional(),
  image_url: z.string().nullable().optional(),
  published: z.string().nullable().optional(),
  author: z.string().nullable().optional(),
});
export type News = z.infer<typeof NewsSchema>;

// ── Player Game Stats (discriminated union) ──────────────────────────────────

export const BasketballStatsSchema = z.object({
  category: z.literal("basketball"),
  pts: z.number().nullable().optional(),
  reb: z.number().nullable().optional(),
  ast: z.number().nullable().optional(),
  stl: z.number().nullable().optional(),
  blk: z.number().nullable().optional(),
  to: z.number().nullable().optional(),
  fg_pct: z.number().nullable().optional(),
  ft_pct: z.number().nullable().optional(),
  three_pct: z.number().nullable().optional(),
  min: z.number().nullable().optional(),
  plus_minus: z.number().nullable().optional(),
});

export const FootballStatsSchema = z.object({
  category: z.literal("football"),
  pass_yds: z.number().nullable().optional(),
  pass_td: z.number().nullable().optional(),
  rush_yds: z.number().nullable().optional(),
  rush_td: z.number().nullable().optional(),
  rec_yds: z.number().nullable().optional(),
  rec_td: z.number().nullable().optional(),
  receptions: z.number().nullable().optional(),
  tackles: z.number().nullable().optional(),
  sacks: z.number().nullable().optional(),
  interceptions: z.number().nullable().optional(),
  pass_rating: z.number().nullable().optional(),
});

export const BaseballStatsSchema = z.object({
  category: z.literal("baseball"),
  ab: z.number().nullable().optional(),
  hits: z.number().nullable().optional(),
  hr: z.number().nullable().optional(),
  rbi: z.number().nullable().optional(),
  runs: z.number().nullable().optional(),
  avg: z.number().nullable().optional(),
  obp: z.number().nullable().optional(),
  slg: z.number().nullable().optional(),
  era: z.number().nullable().optional(),
  strikeouts: z.number().nullable().optional(),
  whip: z.number().nullable().optional(),
});

export const HockeyStatsSchema = z.object({
  category: z.literal("hockey"),
  goals: z.number().nullable().optional(),
  assists: z.number().nullable().optional(),
  points: z.number().nullable().optional(),
  shots: z.number().nullable().optional(),
  saves: z.number().nullable().optional(),
  save_pct: z.number().nullable().optional(),
  plus_minus: z.number().nullable().optional(),
  pim: z.number().nullable().optional(),
  toi: z.string().nullable().optional(),
});

export const SoccerStatsSchema = z.object({
  category: z.literal("soccer"),
  goals: z.number().nullable().optional(),
  assists: z.number().nullable().optional(),
  shots: z.number().nullable().optional(),
  shots_on_target: z.number().nullable().optional(),
  passes: z.number().nullable().optional(),
  pass_pct: z.number().nullable().optional(),
  tackles: z.number().nullable().optional(),
  xg: z.number().nullable().optional(),
  xa: z.number().nullable().optional(),
  yellow_cards: z.number().nullable().optional(),
  red_cards: z.number().nullable().optional(),
});

export const TennisStatsSchema = z.object({
  category: z.literal("tennis"),
  aces: z.number().nullable().optional(),
  double_faults: z.number().nullable().optional(),
  first_serve_pct: z.number().nullable().optional(),
  break_points_won: z.number().nullable().optional(),
  sets_won: z.number().nullable().optional(),
  sets_lost: z.number().nullable().optional(),
  winners: z.number().nullable().optional(),
  unforced_errors: z.number().nullable().optional(),
});

export const MMAStatsSchema = z.object({
  category: z.literal("mma"),
  strikes_landed: z.number().nullable().optional(),
  sig_strikes: z.number().nullable().optional(),
  takedowns: z.number().nullable().optional(),
  sub_attempts: z.number().nullable().optional(),
  knockdowns: z.number().nullable().optional(),
  control_time: z.string().nullable().optional(),
  result: z.string().nullable().optional(),
  method: z.string().nullable().optional(),
});

export const F1StatsSchema = z.object({
  category: z.literal("motorsport"),
  grid_position: z.number().nullable().optional(),
  finish_position: z.number().nullable().optional(),
  laps: z.number().nullable().optional(),
  points: z.number().nullable().optional(),
  fastest_lap: z.string().nullable().optional(),
  pit_stops: z.number().nullable().optional(),
  status: z.string().nullable().optional(),
  dnf: z.boolean().default(false),
  constructor: z.string().nullable().optional(),
});

export const EsportsStatsSchema = z.object({
  category: z.literal("esports"),
  kills: z.number().nullable().optional(),
  deaths: z.number().nullable().optional(),
  assists: z.number().nullable().optional(),
  kda: z.number().nullable().optional(),
  damage: z.number().nullable().optional(),
  headshot_pct: z.number().nullable().optional(),
  rating: z.number().nullable().optional(),
});

export const GolfStatsSchema = z.object({
  category: z.literal("golf"),
  score: z.number().nullable().optional(),
  score_to_par: z.number().nullable().optional(),
  rounds: z.number().nullable().optional(),
  birdies: z.number().nullable().optional(),
  bogeys: z.number().nullable().optional(),
  eagles: z.number().nullable().optional(),
  fairway_pct: z.number().nullable().optional(),
  gir_pct: z.number().nullable().optional(),
  putts: z.number().nullable().optional(),
  position: z.number().nullable().optional(),
});

export const PlayerGameStatsSchema = z.discriminatedUnion("category", [
  BasketballStatsSchema,
  FootballStatsSchema,
  BaseballStatsSchema,
  HockeyStatsSchema,
  SoccerStatsSchema,
  TennisStatsSchema,
  MMAStatsSchema,
  F1StatsSchema,
  EsportsStatsSchema,
  GolfStatsSchema,
]);
export type PlayerGameStats = z.infer<typeof PlayerGameStatsSchema>;
