/* eslint-disable @typescript-eslint/no-explicit-any */

export type SortDir = "asc" | "desc";

export interface ColumnDef {
  key: string;
  label: string;
  format?: (v: any) => string;
}

// ── Formatters ──────────────────────────────────────────────
export const pctFmt = (v: any) => (v != null && !isNaN(Number(v)) ? `${(Number(v) * 100).toFixed(1)}%` : "—");
export const numFmt = (v: any) => (v != null && !isNaN(Number(v)) ? String(Number(v).toFixed(1)) : "—");
export const intFmt = (v: any) => (v != null && !isNaN(Number(v)) ? String(Math.round(Number(v))) : "—");
export const avgFmt = (v: any) => (v != null && !isNaN(Number(v)) ? Number(v).toFixed(3) : "—");
export const rawPctFmt = (v: any) => (v != null && !isNaN(Number(v)) ? `${Number(v).toFixed(1)}%` : "—");

// ── Player column definitions per sport ─────────────────────
export const PLAYER_COLUMNS: Record<string, ColumnDef[]> = {
  nba: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "pts", label: "PPG", format: numFmt },
    { key: "reb", label: "RPG", format: numFmt },
    { key: "ast", label: "APG", format: numFmt },
    { key: "fg_pct", label: "FG%", format: pctFmt },
    { key: "three_pct", label: "3P%", format: pctFmt },
    { key: "ft_pct", label: "FT%", format: pctFmt },
  ],
  nfl: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "passing_yards", label: "Pass Yds", format: numFmt },
    { key: "passing_tds", label: "Pass TD", format: numFmt },
    { key: "rushing_yards", label: "Rush Yds", format: numFmt },
    { key: "rushing_tds", label: "Rush TD", format: numFmt },
    { key: "receptions", label: "Rec", format: numFmt },
    { key: "receiving_yards", label: "Rec Yds", format: numFmt },
  ],
  nhl: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "goals", label: "Goals", format: intFmt },
    { key: "assists", label: "Assists", format: intFmt },
    { key: "points", label: "Points", format: intFmt },
    { key: "plus_minus", label: "+/-", format: intFmt },
    { key: "shots", label: "SOG", format: intFmt },
  ],
  mlb: [
    { key: "player_name", label: "Player" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "ab", label: "AB", format: numFmt },
    { key: "hits", label: "H", format: numFmt },
    { key: "hr", label: "HR", format: numFmt },
    { key: "rbi", label: "RBI", format: numFmt },
    { key: "runs", label: "R", format: numFmt },
    { key: "avg", label: "AVG", format: avgFmt },
    { key: "obp", label: "OBP", format: avgFmt },
    { key: "slg", label: "SLG", format: avgFmt },
  ],
  wnba: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "pts", label: "PPG", format: numFmt },
    { key: "reb", label: "RPG", format: numFmt },
    { key: "ast", label: "APG", format: numFmt },
    { key: "fg_pct", label: "FG%", format: pctFmt },
    { key: "three_pct", label: "3P%", format: pctFmt },
    { key: "ft_pct", label: "FT%", format: pctFmt },
  ],
  atp: [
    { key: "player_name", label: "Name" },
    { key: "gp", label: "Matches", format: intFmt },
    { key: "aces", label: "Aces", format: intFmt },
    { key: "double_faults", label: "DF", format: intFmt },
    { key: "first_serve_pct", label: "1st Srv%", format: rawPctFmt },
  ],
  wta: [
    { key: "player_name", label: "Name" },
    { key: "gp", label: "Matches", format: intFmt },
    { key: "aces", label: "Aces", format: intFmt },
    { key: "double_faults", label: "DF", format: intFmt },
    { key: "first_serve_pct", label: "1st Srv%", format: rawPctFmt },
  ],
  epl: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "goals", label: "Goals", format: intFmt },
    { key: "assists", label: "Assists", format: intFmt },
    { key: "minutes", label: "Min", format: intFmt },
    { key: "yellow_cards", label: "YC", format: intFmt },
    { key: "red_cards", label: "RC", format: intFmt },
  ],
  bundesliga: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "goals", label: "Goals", format: intFmt },
    { key: "assists", label: "Assists", format: intFmt },
    { key: "minutes", label: "Min", format: intFmt },
    { key: "yellow_cards", label: "YC", format: intFmt },
    { key: "red_cards", label: "RC", format: intFmt },
  ],
  laliga: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "goals", label: "Goals", format: intFmt },
    { key: "assists", label: "Assists", format: intFmt },
    { key: "minutes", label: "Min", format: intFmt },
    { key: "yellow_cards", label: "YC", format: intFmt },
    { key: "red_cards", label: "RC", format: intFmt },
  ],
  seriea: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "goals", label: "Goals", format: intFmt },
    { key: "assists", label: "Assists", format: intFmt },
    { key: "minutes", label: "Min", format: intFmt },
    { key: "yellow_cards", label: "YC", format: intFmt },
    { key: "red_cards", label: "RC", format: intFmt },
  ],
  ligue1: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "goals", label: "Goals", format: intFmt },
    { key: "assists", label: "Assists", format: intFmt },
    { key: "minutes", label: "Min", format: intFmt },
    { key: "yellow_cards", label: "YC", format: intFmt },
    { key: "red_cards", label: "RC", format: intFmt },
  ],
  mls: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "goals", label: "Goals", format: intFmt },
    { key: "assists", label: "Assists", format: intFmt },
    { key: "minutes", label: "Min", format: intFmt },
  ],
  ucl: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "goals", label: "Goals", format: intFmt },
    { key: "assists", label: "Assists", format: intFmt },
    { key: "minutes", label: "Min", format: intFmt },
    { key: "yellow_cards", label: "YC", format: intFmt },
    { key: "red_cards", label: "RC", format: intFmt },
  ],
  nwsl: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "goals", label: "Goals", format: intFmt },
    { key: "assists", label: "Assists", format: intFmt },
    { key: "shots", label: "Shots", format: intFmt },
    { key: "shots_on_target", label: "SOT", format: intFmt },
    { key: "key_passes", label: "KP", format: intFmt },
    { key: "minutes", label: "Min", format: intFmt },
  ],
  ncaab: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "pts", label: "PPG", format: numFmt },
    { key: "reb", label: "RPG", format: numFmt },
    { key: "ast", label: "APG", format: numFmt },
    { key: "stl", label: "SPG", format: numFmt },
    { key: "blk", label: "BPG", format: numFmt },
    { key: "fg_pct", label: "FG%", format: pctFmt },
    { key: "three_pct", label: "3P%", format: pctFmt },
    { key: "ft_pct", label: "FT%", format: pctFmt },
  ],
  ncaaf: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "passing_yards", label: "Pass Yds", format: numFmt },
    { key: "passing_tds", label: "Pass TD", format: numFmt },
    { key: "rushing_yards", label: "Rush Yds", format: numFmt },
    { key: "rushing_tds", label: "Rush TD", format: numFmt },
    { key: "receptions", label: "Rec", format: numFmt },
    { key: "receiving_yards", label: "Rec Yds", format: numFmt },
    { key: "interceptions", label: "INT", format: intFmt },
    { key: "passer_rating", label: "RTG", format: numFmt },
  ],
  ncaaw: [
    { key: "player_name", label: "Name" },
    { key: "team", label: "Team" },
    { key: "gp", label: "GP", format: intFmt },
    { key: "pts", label: "PPG", format: numFmt },
    { key: "reb", label: "RPG", format: numFmt },
    { key: "ast", label: "APG", format: numFmt },
    { key: "stl", label: "SPG", format: numFmt },
    { key: "blk", label: "BPG", format: numFmt },
    { key: "fg_pct", label: "FG%", format: pctFmt },
    { key: "three_pct", label: "3P%", format: pctFmt },
    { key: "ft_pct", label: "FT%", format: pctFmt },
  ],
  ufc: [
    { key: "player_name", label: "Fighter" },
    { key: "gp", label: "Fights", format: intFmt },
    { key: "wins", label: "W", format: intFmt },
    { key: "losses", label: "L", format: intFmt },
    { key: "knockouts", label: "KO", format: intFmt },
    { key: "submissions", label: "Sub", format: intFmt },
    { key: "significant_strikes", label: "Sig Str", format: intFmt },
    { key: "takedowns", label: "TD", format: intFmt },
    { key: "sig_str_pct", label: "Sig Str%", format: rawPctFmt },
    { key: "td_pct", label: "TD%", format: rawPctFmt },
  ],
  csgo: [
    { key: "player_name", label: "Player" },
    { key: "team", label: "Team" },
    { key: "gp", label: "Maps", format: intFmt },
    { key: "kills", label: "Kills", format: numFmt },
    { key: "deaths", label: "Deaths", format: numFmt },
    { key: "assists", label: "Assists", format: numFmt },
    { key: "headshot_pct", label: "HS%", format: rawPctFmt },
    { key: "adr", label: "ADR", format: numFmt },
    { key: "rating", label: "Rating", format: numFmt },
  ],
  lol: [
    { key: "player_name", label: "Player" },
    { key: "team", label: "Team" },
    { key: "gp", label: "Games", format: intFmt },
    { key: "kills", label: "Kills", format: numFmt },
    { key: "deaths", label: "Deaths", format: numFmt },
    { key: "assists", label: "Assists", format: numFmt },
    { key: "cs_per_min", label: "CS/M", format: numFmt },
    { key: "gold_per_min", label: "GPM", format: numFmt },
    { key: "vision_score", label: "VS", format: numFmt },
    { key: "damage", label: "DMG", format: intFmt },
  ],
  dota2: [
    { key: "player_name", label: "Player" },
    { key: "team", label: "Team" },
    { key: "gp", label: "Games", format: intFmt },
    { key: "kills", label: "Kills", format: numFmt },
    { key: "deaths", label: "Deaths", format: numFmt },
    { key: "assists", label: "Assists", format: numFmt },
    { key: "gold_per_min", label: "GPM", format: numFmt },
    { key: "last_hits", label: "LH", format: numFmt },
    { key: "damage", label: "DMG", format: intFmt },
  ],
  valorant: [
    { key: "player_name", label: "Player" },
    { key: "team", label: "Team" },
    { key: "gp", label: "Maps", format: intFmt },
    { key: "kills", label: "Kills", format: numFmt },
    { key: "deaths", label: "Deaths", format: numFmt },
    { key: "assists", label: "Assists", format: numFmt },
    { key: "headshot_pct", label: "HS%", format: rawPctFmt },
    { key: "adr", label: "ADR", format: numFmt },
    { key: "rating", label: "Rating", format: numFmt },
  ],
  f1: [
    { key: "player_name", label: "Driver" },
    { key: "team", label: "Team" },
    { key: "gp", label: "Races", format: intFmt },
    { key: "position", label: "Pos", format: intFmt },
    { key: "points", label: "Points", format: numFmt },
    { key: "grid", label: "Grid", format: intFmt },
    { key: "fastest_lap", label: "FL" },
    { key: "laps_completed", label: "Laps", format: intFmt },
    { key: "wins", label: "Wins", format: intFmt },
    { key: "podiums", label: "Podiums", format: intFmt },
  ],
  golf: [
    { key: "player_name", label: "Player" },
    { key: "gp", label: "Events", format: intFmt },
    { key: "score", label: "Score", format: intFmt },
    { key: "rounds", label: "Rnds", format: intFmt },
    { key: "birdies", label: "Birdies", format: intFmt },
    { key: "eagles", label: "Eagles", format: intFmt },
    { key: "fairway_pct", label: "FW%", format: rawPctFmt },
    { key: "gir_pct", label: "GIR%", format: rawPctFmt },
    { key: "putts_per_round", label: "Putts/Rnd", format: numFmt },
    { key: "scoring_avg", label: "Avg", format: numFmt },
  ],
};

// ── MLB pitcher columns ─────────────────────────────────────
export const MLB_PITCHER_COLUMNS: ColumnDef[] = [
  { key: "player_name", label: "Player" },
  { key: "team", label: "Team" },
  { key: "gp", label: "GP", format: intFmt },
  { key: "wins", label: "W", format: intFmt },
  { key: "losses", label: "L", format: intFmt },
  { key: "era", label: "ERA", format: avgFmt },
  { key: "innings_pitched", label: "IP", format: numFmt },
  { key: "strikeouts", label: "K", format: intFmt },
  { key: "walks", label: "BB", format: intFmt },
  { key: "hits_allowed", label: "H", format: intFmt },
  { key: "earned_runs", label: "ER", format: intFmt },
  { key: "whip", label: "WHIP", format: avgFmt },
];

// ── Team columns ────────────────────────────────────────────
export const TEAM_COLUMNS: ColumnDef[] = [
  { key: "name", label: "Team" },
  { key: "wins", label: "W", format: intFmt },
  { key: "losses", label: "L", format: intFmt },
  { key: "points_for", label: "PPG", format: numFmt },
  { key: "points_against", label: "OPPG", format: numFmt },
  { key: "diff", label: "Diff", format: numFmt },
];

// ── Default sort column per sport ───────────────────────────
export const DEFAULT_SORT: Record<string, string> = {
  nba: "pts",
  nfl: "passing_yards",
  nhl: "points",
  mlb: "avg",
  wnba: "pts",
  atp: "gp",
  wta: "gp",
  epl: "goals",
  bundesliga: "goals",
  laliga: "goals",
  seriea: "goals",
  ligue1: "goals",
  mls: "goals",
  ucl: "goals",
  nwsl: "goals",
  ncaab: "pts",
  ncaaf: "passing_yards",
  ncaaw: "pts",
  ufc: "gp",
  csgo: "kills",
  lol: "kills",
  dota2: "kills",
  valorant: "kills",
  f1: "points",
  golf: "points",
};
